services:
  vector-match:
    build:
      context: ./vectorMatch
    stdin_open: true  # Equivalent to `-i`
    tty: true         # Equivalent to `-t`
    depends_on:
      - vector-db
      - ollama
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    networks:
      - app_network

  vector-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: pgvectors
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persistent storage for database
      - ./init-scripts:/docker-entrypoint-initdb.d  # Initialization scripts
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/data
      - ./entrypoint.sh:/entrypoint.sh
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
  ollama_data:
